export const featureFlags = {
  navigation: {
    showCustomerOverview: true,
    showInvoiceOverview: true,
    showNewInvoice: true,
  },
  crmOverview: {
    enabled: true,
    showIdColumn: true,
    showCustomerNumberColumn: true,
    showTypeColumn: true,
    showNameColumn: true,
    showEmailColumn: true,
    showCreatedAtColumn: false,
    showUpdatedAtColumn: false,
    includePersons: true,
    includeCompanies: true,
    enableCompanyCreation: true,
    enablePersonCreation: true,
  },
  personView: {
    showPerson: true,
    showCustomerNumber: true,
    showCreatedAt: true,
    showAddresses: true,
    showBirthdate: true,
  },
  companyView: {
    showCompanyName: true,
    showCustomerNumber: true,
    showCreatedAt: true,
    showAddresses: true,
  },
  companyEdit: {
    showNameField: true,
    showCustomerNumberField: true,
    showAddresses: true,
    showContactDetails: true,
    showPaymentInformation: true,
    showConditions: true,
    showAdditional: true,
  },
  personEdit: {
    showSalutation: true,
    showFirstname: true,
    showLastname: true,
    showCustomerNumber: true,
    showBirthdate: true,
    showAddresses: true,
    showContactDetails: true,
    showPaymentInformation: true,
    showConditions: true,
    showAdditional: true,
  },
  omOverview: {
    enabled: true,
    showIdColumn: true,
    showCreatedAtColumn: true,
    showUpdatedAtColumn: true,
    includeInvoices: true,
    enableInvoiceCreation: true,
  },
};
